## Get Dramas
GET http://localhost:3000/dramas

## Get Actors
GET http://localhost:3000/actors

##Get single drama by Id
GET http://localhost:3000/dramas/6467e9665fde0f46e4e7c18c

##Get single actor by Id
GET http://localhost:3000/actors/6467ebb65fde0f46e4e7c18d

### Add Drama
POST http://localhost:3000/dramas HTTP/1.1
content-type: application/json
{
    "title": "Healer",
    "content": "A decades-old incident involving a group of five friends who ran an illegal pro-democracy broadcasting station during the Fifth Republic in South Korea brings together three different people—an illegal night courier with the codename Healer (Ji Chang-wook) who possesses top-notch fighting skills, a reporter from a second-rate tabloid news website (Park Min-young), and a famous journalist at a major broadcast station (Yoo Ji-tae).[9][10][11] While trying to uncover the truth from that 1992 incident and a series of present day murders, they grow into honest reporters who try to blur the lines of conflict between truth and reality, even if that means fighting media honchos.",
    "chapters": "20",
    "date": "December 8, 2014 – February 10, 2015",
    "genre": "Action - Thriller - Romance",
    "producer": "Kim Jong-hak Production",
    "writer": "Song Ji-na"
}

### Add actor
POST http://localhost:3000/actors HTTP/1.1
content-type: application/json
{
    "actorName": "Ji Chang Wook",
    "characterName": "Seo Jung Hoo",
    "birthdate": "july 5, 1987",
    "nationality": "Korean"
}