const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger-output.json'
const endpointsFiles = ['./routes/index.js']

const doc = {
  info: {
    version: "1.0.0",
    title: "K-Dramas API",
    description: "Documentation generated by swagger-autogen."
  },
  host: 'jatsi341-assignment5.onrender.com',
  //basePath: "/",
  schemes: ['https']
  //consumes: ['application/json'],
  //produces: ['application/json'],
  //tags:[
   // {
   //   "name": "Contacts",
    //  "description": "Endpoints"
   // }
  //]
}

swaggerAutogen(outputFile, endpointsFiles, doc)