const { oauth2 } = require('googleapis/build/src/apis/oauth2')

const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger-output.json'
const endpointsFiles = ['./routes/index.js']

const doc = {
  info: {
    version: "1.0.0",
    title: "K-Dramas API",
    description: "Documentation generated by swagger-autogen."
  },
  host: 'jatsi341-assignment5.onrender.com',
    securitySchemes:{
      oAuth:{
        type: "oauth2",
        description: "This API uses OAuth 2",
        flows: {
            clientCredentials:{
            tokenUrl: 'https://github.com/login/oauth/access_token',
            scopes: {
              /*put_drama: "Add a drama",
              post_drama: "Edit a drama",
              delete_drama: "Delete a drama",
              put_actor: "Add an actor",
              post_actor: "Edit an actor",
              delete_actor: "Delete an actor"*/
            }
          }
        }
      }
    },

  security: {
    oAuthNoScopes: []
    /*oAuth:
    put_drama,
    post_drama,
    delete_drama,
    put_actor,
    post_actor,
    delete_actor*/
  },
  //basePath: "/",
  schemes: ['https']
  
  
  //consumes: ['application/json'],
  //produces: ['application/json'],
  //tags:[
   // {
   //   "name": "Contacts",
    //  "description": "Endpoints"
   // }
  //]
}

swaggerAutogen(outputFile, endpointsFiles, doc)